### ISSUE TITLE
Thinking style feedback

### ISSUE THREAD

**Issue by ChristineSchatz** [cjmanetta/cjmanetta.github.io#11]
Hey Charlotte,
First of all, I love your design and really like the font colors and styles you used. Really clean!! I noticed a small error in the first paragraph of your Thinking Style post. It says &emdash; (this was supposed to be CSS?). It's in the 3rd to last sentence. 
One more feedback and that's it :) I think your content would look really nice centered, instead of left-aligned. Otherwise, fantastic job!

You're abstract sequential dominant? I find that super interesting, because that was my least dominant thinking style, and I thought you were the best pair I've worked with so far. You weren't afraid to communicate your ideas. You were collaborative, considerate, and most of all, you were okay with our silences. I think that's so important. Sometimes I just need to zone out (or in!) to think. 
-C

**Comment by cjmanetta** [comment]
Hey Chrstine,

Thanks for the great feedback. The &emdash; was actually supposed to be &mdash; which is the html entity for an em dash. Good catch! 

About the centering, I am planning to put blog navigation on the right hand side eventually. If you can imagine it with right hand navigation -  what do you think about centered vs left-aligned in that case? I am kind of unsure about which one is best. I feel like i've seen both.

You were definitely my most compatible pair too! Thats funny... I felt exactly the same things about you that you said about me! Can you move to SF for on-site? : )

Char

**Comment by ChristineSchatz** [comment]
Char,
Now that I'm looking at your site on a 13-inch (before I was on a bigger monitor), the left-alignment looks less obvious. And since you're planning on a right hand side blog navigation, I think both centered and left-aligned could work in that case, depending on how wide the navigation will be! Either way I really like your color scheme and clean design. By the way, where did you find the icons for twitter, github, etc? I found this <i class> thing for them but can't get them the right size.

And more about pairing! I'll send you an email :)
