### ISSUE TITLE
Good explanation of Map

### ISSUE THREAD

**Issue by chrisswk** [cjmanetta/cjmanetta.github.io#14]
Ruby-Doc can be difficult to parse and you did a good job of emphasizing the distinction between map, each and what they return.

One constructive piece of feedback: there are a couple of techniques you can use to show code on your website.  I like gist.github.com and using their embedded code feature.  Its probably good practice that you created a border around your paragraph elements for code and changed the font but gist will even color code your code sample based on the language you use and looks pretty good.  So check it out(if you feel like it!)

**Comment by cjmanetta** [comment]
Thanks for the tip Chris!
